<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>YA_Defender.Service</RootNamespace>
    <LangVersion>12</LangVersion>
    <AssemblyName>YA_Defender.Service</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\YA_Defender.Shared\YA_Defender.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
  </ItemGroup>

</Project>
